[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chess"
version = "0.0.1"
description = "A simple chess program"
readme = "README.md"
requires-python = ">=3.8"

[tool.black]
target-version = ["py39"]
